apiVersion: v1
kind: Service
metadata:
  namespace: application
  name: backend-api
spec:
  type: ClusterIP
  selector:
    app: backend-api
  ports:
  - name: listen-port
    port: 8080
    targetPort: 8080
  - name: health-check-port
    port: 9000
    targetPort: 9000
