apiVersion: v1
kind: Service
metadata:
  namespace: auth
  name: keycloak
spec:
  type: ClusterIP
  selector:
    app: keycloak
  ports:
    - name: listen-port
      port: 8080
      targetPort: 8080
    - name: health-check-port
      port: 9000
      targetPort: 9000
