apiVersion: v1
kind: Service
metadata:
  namespace: application
  name: oauth2-proxy
spec:
  type: ClusterIP
  selector:
    app: oauth2-proxy
  ports:
    - name: listen-port
      port: 4180
      targetPort: 4180
