apiVersion: v1
kind: Service
metadata:
  namespace: auth
  name: postgres
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
    - name: listen-port
      port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  namespace: application
  name: postgres
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
    - name: listen-port
      port: 5432
      targetPort: 5432
