apiVersion: v1
kind: ConfigMap
metadata:
  namespace: application
  name: oauth2-proxy
data:
  OAUTH2_PROXY_PROVIDER: keycloak-oidc
  OAUTH2_PROXY_HTTP_ADDRESS: 0.0.0.0:4180
  OAUTH2_PROXY_CLIENT_ID: demo
  OAUTH2_PROXY_READY_PATH: /oauth2/ready
  OAUTH2_PROXY_EMAIL_DOMAINS: "*"
  OAUTH2_PROXY_CODE_CHALLENGE_METHOD: S256
  OAUTH2_PROXY_COOKIE_DOMAINS: .localhost
  OAUTH2_PROXY_COOKIE_EXPIRE: 72h
  OAUTH2_PROXY_COOKIE_REFRESH: 29m
  OAUTH2_PROXY_COOKIE_SECURE: "true"
  OAUTH2_PROXY_WHITELIST_DOMAINS: "*.localhost"
  OAUTH2_PROXY_OIDC_ISSUER_URL: http://sso.localhost/realms/demo
  OAUTH2_PROXY_REDIRECT_URL: http://backend-api.localhost/oauth2/callback
  OAUTH2_PROXY_REVERSE_PROXY: "true"
  OAUTH2_PROXY_SET_AUTHORIZATION_HEADER: "true"
  OAUTH2_PROXY_PASS_AUTHORIZATION_HEADER: "true"
  OAUTH2_PROXY_UPSTREAMS: http://backend-api:8080
  OAUTH2_PROXY_INSECURE_OIDC_ALLOW_UNVERIFIED_EMAIL: "true"
  OAUTH2_PROXY_FORCE_JSON_ERRORS: "true" # Authenticate 失敗時不做導頁，而是固定回傳 empty json object
  OAUTH2_PROXY_SKIP_PROVIDER_BUTTON: "true"
  OAUTH2_PROXY_SKIP_AUTH_PREFLIGHT: "true" # 讓 Oauth2 Proxy 接收到 OPTIONS request 時不做 Authentication 行為（可以解決 Broswer 做 preflight request 時，Oauth2 Proxt 回覆 401 導致 CORS 的問題）
  OAUTH2_PROXY_REAL_CLIENT_IP_HEADER: "X-Forwarded-For" # 指定 Oauth2 Proxy 透過 X-Forwarded-For header 辨認 Client IP
  # OAUTH2_PROXY_TRUSTED_IPS: "127.0.0.1" # 要讓 Oauth2 Proxy 信任的 IP List，此選項會讓這個 IP List 繞過 Oauth2 Proxy 的 Authentication 行為
  OAUTH2_PROXY_SHOW_DEBUG_ON_ERROR: "true" # show detailed error information on error pages (WARNING: this may contain sensitive information - do not use in production)
