apiVersion: v1
kind: ConfigMap
metadata:
  namespace: sso
  name: postgres
data:
  POSTGRES_DB: keycloak
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: application
  name: postgres
data:
  POSTGRES_DB: backend-api
